[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  external_node_modules = ["sqlite3"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200